# Generated by Django 3.2.18 on 2024-02-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='edited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thought',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thought',
            name='public',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
